= Pflichtenheft
:project_name: Projektname
== __{project_name}__

[options="header"]
[cols="1, 1, 1, 1, 4"]
|===
|Version | Status      | Bearbeitungsdatum   | Autoren(en) |  Vermerk
|0.1     | In Arbeit   | 10.10.2021          | Autor       | Initiale Version
|0.2     | In Arbeit   | 22.10.2021          | Mirek Král  | Ergänzung des Pflichtenhesftes
|0.3     | In Arbeit   | 22.10.2021          | Sophie Schulze  | Ergänzung: Beschreibung der Use Cases
|0.4     | In Arbeit   | 22.10.2021          | Song Bai    | Ergänzung der Beschreibung
|0.5     | In Arbeit   | 25.10.2021          | Alle Gruppenmitglieder | Ergänzung des Pflichtenhesftes
|===

== 1. Inhaltsverzeichnis
Dieses Dokument benötigt ein Inhaltsverzeichnis. Es existieren mehrere Einbindungsmöglichkeiten.
_Inhalt_
 
  1. Inhaltsverzeichnis
  2. Zusammenfassung
  3. Aufgabenstellung
  4. Produktnutzung
  5. Interessensgruppen (Stakeholders)
  6. Systemgrenze und Top-Level-Architektur
  
  6.1.Kontextdiagramm
  6.2. Top-Level-Architektur
  6.3. Anwendungsfälle
  
  7. Use-Case
  
  7.1  Akteure
  7.2 Überblick Anwendungsfalldiagramm
  7.3 Anwendungsfallbeschreibungen
  
  8. Funktionale Anforderungen
  9. Nicht-Funktionale Anforderungen
  
  9.1 Qualitätsziele
  9.2 Konkrete Nicht-Funktionale Anforderungen
  
  10. GUI Prototyp
  11. Datenmodell
  
  11.1 Überblick: Klassendiagramm
  11.2 Klassen und Enumerationen
  
  12. Akzeptanztestfälle
  13. Glossar
  14. Offene Punkte

== 2. Zusammenfassung
Eine kurze Beschreibung des Dokuments. Wenige Absätze.

== 3. Aufgabenstellung und Zielsetzung
Text aus Aufgabenstellung kopieren und ggfs. präzisieren.
Insbesondere ergänzen, welche Ziele mit dem Abschluss des Projektes erreicht werden sollen.

Lotterie 

In unserem kleinen Nachbarland Gamblien ist die staatlich betriebene Lotterie Mach Dein Glück!! sehr populär. In Staatsbesitz befindet sich auch das weitverbreitete Netz an Annahmestellen.
Gambliens Wirtschaftsminister Lottermann plant den Einstieg in die "virtuelle Lotterie", um auch Ausländer als Kunden zu gewinnen. Vorbereitend sollen der aktuelle Betrieb der Lotterie und der Annahmestellen auf Computer umgestellt und auf dieser Basis neue Dienste erprobt werden.
Aktuell gibt es bei Mach Dein Glück!! eine Zahlenlotterie mit wöchentlicher Ziehung und ein Fußballtoto.
Die Lotterie Mach Dein Glück!! ist eine ganz konventionelle Lotterie "6 aus 49 mit Zusatzzahl". Tippscheine werden an den Annahmestellen bis zum Samstag eingereicht; am Sonntag erfolgt unter strenger notarieller Aufsicht die Ziehung.
Das Fußballtoto bezieht sich mangels eigener Liga auf die oberen beiden Klassen der deutschen Bundesliga. Tippscheine können bis 24 Stunden vor Beginn des Spieltags (evtl. auf mehrere Spieltage verteilt und erst mit dem letzten Nachholspiel beendet) in Bundesliga bzw. Pokalrunden eingereicht werden.
Bei der Zahlenlotterie können derzeit neben Einzeltippscheinen auch Dauertippscheine (monatlich, halb- bzw. ganzjährig) erworben werden. Tippscheine für das Fußballtoto können ab Veröffentlichung der Spielkalender beliebig im Voraus ausgefüllt und abgegeben werden. Nach Minister Lottermanns Plänen soll das Angebot künftig gemäß den neuen Medien flexibler gestaltet sein:

• Es werden Gewinngemeinschaften unterstützt. Beim Einrichten einer Gewinngemeinschaft wird von der Lotterie ein Gemeinschafts-Passwort vergeben. Wer das Gemeinschafts-Passwort kennt, darf für die Gemeinschaft einen Tipp abgeben und darf seinerseits an Personen Mitglieder-Passwörter vergeben. Mit dem Mitglieder-Passwort kann die Person ihre Anteile (ganzzahlige Vielfache des Grundeinsatzes) bis jeweils vor Wettschluss (gegen Bar- bzw. Vorauszahlung) erhöhen oder verringern bzw. zeitweilig ganz aussetzen.

• Änderungen am Tipp bzw. Einsatz sind bis jeweils 5 Minuten vor Beginn einer Auslosung bzw. eines Fußballspieltags möglich.

• An die Stelle von Bareinzahlung sollen künftig Abbuchungen von Konten bei der Lotteriebank treten, die jeder Kunde dort einrichtet und auf die er bar oder per Überweisung rechtzeitig seine Einsätze überträgt. Von diesem Konto werden (in der Reihenfolge der Auslosungen) Einsätze abgebucht. Bei nicht ausreichender Deckung erhält der Kunde eine entsprechende Mitteilung und nimmt an dieser Verlosung nicht teil. Je Mitteilung wird eine Gebühr von 2 € erhoben; nach zehn Mitteilungen wird der Kunde vorläufig aus seinen Gewinngemeinschaften entfernt.

• Administratoren der Lotterie sollen die Möglichkeit haben, jederzeit eine Übersicht über die abgegebenen Wetten der Kunden und die finanzielle Situation (Gewinne/Verluste) der Lotterie nach dem jeweiligen Ziehungstagen und Spieltagen zu bekommen.

• Minister Lottermann hat unter dem Aktenzeichen "MDG 2000" eine Ausschreibung veröffentlicht, und um Einreichung geeigneter, künftig ausbaubarer Prototypen für ein solches System gebeten. Ihr SalesPoint-Team hat zufällig davon erfahren und beabsichtigt, an dem Wettbewerb teilzunehmen.
Die Lotteriebetreiber wären daran interessiert, ihre Fußballtoto-Daten direkt und aktuell aus dem Internet zu beziehen. Wenn der Prototyp dies demonstrieren würde, sähe man das als ein besonderes Plus an.

== 4. Produktnutzung
In welchem Kontext soll das System später genutzt werden? Welche Rahmenbedingungen gelten?
Zusätzlich kurze Einleitung für fachfremde Personen

Das System soll die Struktur der Lotterie digitalisieren. Die Kuden durfen online wetten, Tippscheine ausfüllen und sich über Spielregeln informieren ohne an die Filiale vorbei zu kommen. Nebenbei soll das System die Welt der Lotterie auch internationalen Kunden eröffnen. Vorteil ist, dass die Online-Lotterie 24/7 geöffnet ist.

Das System soll von folgenden Web-Browsers unterstütz werden

• Mozila Firefox v93.0+
• Google Chrome 94.0+
• Microsoft Edge 95.0+
• Safari v15.0+

== 5. Interessensgruppen (Stakeholders)
Welche realen und juristischen Personen(-gruppen) haben Einfluss auf die Anforderungen im Projekt?

[options="header", cols="5h, ^1, ^1, ^1"]
|===
|Name            | Priorität (1..5) | Beschreibung                                                                             | Ziele
|André Schnidt   | 5                | Der Auftraggeber unseren Projektes                                                      a| 
• Kundenbereich erweitern
• Digitalisierung
• Geld sparen
• Effizienz der Struktur
|Kunden          | 5                | Sie stellen die grösste Interessengruppe dar und sorgen für das Einkommen der Lotterie. a| 
• Geld gweinnen
• intuitive Handhabung
• gute Kunden-Service
|Administrator   | 3                | Er behält den Überblick über den Gewinn und die Verluste der Lotterie.                  a|
• Überblick über Finanzen haben
|Entwickler      | 3                | Sie sind für die Entwicklung/Programmierung und Wartung der Website zuständig.          a| 
• leicht verstehbarer / aufgerämter Code
• keiner ,,Bananaware"
• leicht erweiterbarer Code
|===

Das Interessengruppen sind ausschließlich Erwachsene, d.h. Personen ab 18 Jahre alt.

== 6. Systemgrenze und Top-Level-Architektur

=== 6.1. Kontextdiagramm
Das Kontextdiagramm zeigt das geplante Software-System in seiner Umgebung. Zur Umgebung gehören alle Nutzergruppen des Systems und Nachbarsysteme. Die Grafik kann auch informell gehalten sein. Überlegen Sie sich dann geeignete Symbole. Die Grafik kann beispielsweise mit Visio erstellt werden. Wenn nötig, erläutern Sie diese Grafik.

=== 6.2. Top-Level-Architektur
Dokumentieren Sie ihre Top-Level-Architektur mit Hilfe eines Komponentendiagramm.

=== 6.3. Anwendungsfälle

== 7. Use-Cases

=== 7.1  Akteure

Akteure sind die Benutzer des Software-Systems oder Nachbarsysteme, welche darauf zugreifen. Dokumentieren Sie die Akteure in einer Tabelle. Diese Tabelle gibt einen Überblick über die Akteure und beschreibt sie kurz. Die Tabelle hat also mindestens zwei Spalten (Akteur Name und Kommentar).
Weitere relevante Spalten können bei Bedarf ergänzt werden.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
[cols="1,4"]
|===
|Name                         |Beschreibung
|Kunde                        |Der Kunde kann alles machen, was der registrierter Benutzer. Der Unterschied ist, er kann hauptsächlich bezahlen.
|registrierter Benutzer       |Dem registrierten Benutzer wirden die eigentlichen Funktionalitäten der Internet-Lotterie eröffnet.

Registrierter Benutzer hat die Möglichkeit sich entweder an der Fußballtoto oder der Zahlenlotterie teilzunehmen. Dafür muss er sine virtuelle Portemonnaie mit Geld aufladen. Zusätzlich kann er sein Passwort ändern.
|unregistrierter Benutzer     |Der unregistrierte Benutzer ist als die Person angesehen, die beispielsweise das Web-Portal der Lotterie zum ersten Mal besucht, d.h. Ausländer, bzw. neue potenzielle Kunden. 

Er kann sich das Katalog der Fußballspiele anschauen, evtl. Spielregeln der Zahlenloterie durchlesen. Weiterhin kann er sich registrieren, was schließlich seine Rolle als unregistrierter Benutzer beendet.
|Administrator                |Dieser ist im meisten der Zeit nur ein gewisser Zuschauer der ganzen Struktur. Er schaut sich die generierte Statistik. Er kann im Laufe des Betriebes mit neunen Funktionalitäten kommen, die ein neues Service für die Kunden darstellen.
|Lotterie (System)            |Diese ist eine virtuelle Rolle, die für das allgemeine Betrieb der ganzen Struktur sorgt. Sie speichert alle registrierte Benutzer, generiert Passwörter für Gewinnsgemeinschaftsgruppen, grundet und erweitert die Statistik der Vurluste und Gewinne. 

Bemerkung: Sie bekommt einen offiziellen Name später in der Entwicklung.
|===

=== 7.2 Überblick Anwendungsfalldiagramm
Anwendungsfall-Diagramm, das alle Anwendungsfälle und alle Akteure darstellt

=== 7.3 Anwendungsfallbeschreibungen
Dieser Unterabschnitt beschreibt die Anwendungsfälle. In dieser Beschreibung müssen noch nicht alle Sonderfälle und Varianten berücksichtigt werden. Schwerpunkt ist es, die wichtigsten Anwendungsfälle des Systems zu finden. Wichtig sind solche Anwendungsfälle, die für den Auftraggeber, den Nutzer den größten Nutzen bringen.
Für komplexere Anwendungsfälle ein UML-Sequenzdiagramm ergänzen.
Einfache Anwendungsfälle mit einem Absatz beschreiben.
Die typischen Anwendungsfälle (Anlegen, Ändern, Löschen) können zu einem einzigen zusammengefasst werden.

In Folgenden werden die im Anwendungsfalldiagramm gezeigten Anwendungsfälle im Detail beschrieben.

[cols="1h, 3"]
[[UC01]]
|===
|ID                         |**<<UC01>>**
|Name                       |Fußballspiele anschauen          
|Beschreibung               |Der Nutzer kann den Fußballwettenkatalog aufrufen, um zu sehen auf welche Fußballspiele man wetten kann.
|Akteur                     |alle Nutzer der Website
|Auslöser                   |(später: Durch Klicken auf den Menüpunkt Fußballkatalog)
|Vorbedingung               |keine 
|Grundlegende Schritte     a|
_Fußballspiele anschauen:_ 

  1. Nutzer klickt auf Menüpunkt Fußballkatalog.
  2. Nutzer sieht Liste mit kommenden Fußballspielen
 
|Extensions                 |-
|Funktionale Anforderungen  |tba
|===


[cols="1h, 3"]
[[UC02]]
|===
|ID                         |**<<UC02>>**
|Name                       |Lottoschein ausfüllen          
|Beschreibung               |-
|Akteur                     |registrierter Benutzer
|Auslöser                   |-
|Vorbedingung               |Der Benutzer muss sich registrieren und eingeloggt werden, um Lotoscheine ausfüllen zu können. 
|Grundlegende Schritte      |-
|Extensions                 |-
|Funktionale Anforderungen  |-
|===



[cols="1h, 3"]
[[UC04]]
|===
|ID                         |**<<UC04>>**
|Name                       |Passwort ändern          
|Beschreibung               |Der Benutzer soll sein eigenes Passwort ändern können.
|Akteur                     |registrierter Benutzer
|Auslöser                   |-
|Vorbedingung               |Der Benutzer muss sich registrieren und eingeloggt werden. 
|Grundlegende Schritte     a|

* Nutzer klikt auf Einstellungen "change Password".
* Nutzer geben altes Passwort, neues Passwort ab, und wiederholt sich nochmal neues Passwort um alle zu bestätigen.
** Falls die Eingabe korrekt war: Nutzer wird zur Startseite weitergeleitet.
** Sonst: Eine Fehlermeldung wird angezeigt.

|Extensions                 |-
|Funktionale Anforderungen  |-
|===


[cols="1h, 3"]
[[UC05]]
|===
|ID                         |**<<UC05>>**
|Name                       |Registrierung          
|Beschreibung               |Damit sich ein potenzieller Kunde aktiv an der Zahlenlotterie, bzw. Fußballtoto teilnehmen kann, muss ihm ermöglicht werden sich zu registrieren. Diese Funktion bildet die Grundlage neuer Funktionalitäten z.B. Passwort ändern, Ein-/Ausloggen, Geldüberweisen, etc..
|Akteur                     |unregistrierter Benutzer
|Auslöser                   |
_Registration:_ Unregistrierter Benutzer möchte den Zutritt zur Teilnahme an den jeweiligen Angebote der Lotterie.
|Vorbedingung               |Der Benutzer wurde nicht bereits registriert.
|Grundlegende Schritte     a|
_Resgistration:_ 

  1. Eingabe eines bereits nicht besetzten Benutzernamens.
  2. Eingabe eines Passwortes (Mit Hinsicht auf die Kriterien)
 
|Extensions                 |-
|Funktionale Anforderungen  |-
|===


[cols="1h, 3"]
[[UC09]]
|===
|ID                         |**<<UC09>>**
|Name                       |Gewinngruppe erstellen          
|Beschreibung               |Ein angemeldeter/registrierter Nutzer kann eine Gewinngemeinschaft erstellen. Das System generiert für die Gruppe ein Passwort,
das der Ersteller an neue Mitglieder weitergeben kann.
|Akteur                     |registrierter Nutzer
|Auslöser                   |tba
|Vorbedingung               |Der Nutzer ist bereits im System registriert, hat also einen Benutzernamen sowie ein Passwort und muss sich vor dem Erstellen der Gruppe anmelden.
|Grundlegende Schritte     a|
_Gewinngemeinschaft erstellen:_ 

  1. Nutzer meldet sich an.
  2. Nutzer klickt auf Gewinngemeinschaft erstellen.
  3. System generiert Passwort (hinsichtlich der Kriterien).
  4. System teilt dem Nutzer das Gruppenpasswort mit.
  5. System schickt Bestätigung für Erstellung der Gruppe.
 
|Extensions                 |-
|Funktionale Anforderungen  |tba
|===



[cols="1h, 3"]
[[UC12]]
|===
|ID                         |**<<UC12>>**
|Name                       |Statistik anschauen          
|Beschreibung               |Der Admin soll Statistik über die abgegebenen Wetten anschauen können
|Akteur                     |Administrator
|Auslöser                   |-
|Vorbedingung               |- 
|Grundlegende Schritte     a|

* Admin drückt auf "bet management" in der Navigationsliste.
* Die Liste aller Wetten wird angezeigt.

|Extensions                 |-
|Funktionale Anforderungen  |-
|===


== 8. Funktionale Anforderungen

=== 8.1 Muss-Kriterien
_Muss-Kriterien_ 

  1. Statistik erstellen
  2. Bei Fußballtoto eine Wette abgeben und eine Liste mit kommenden Spiele anschauen.
  3. Bei Zahlenloterie Lottoschein ausfüllen.
  4. Registration für Kunden.

=== 8.2 Kann-Kriterien
Anforderungen die das Programm leisten können soll, aber für den korrekten Betrieb entbehrlich sind.

_Kann-Kriterien_ 

  1. Mehrsprachige Web-Seite.
  2. Passwortänderung.

== 9. Nicht-Funktionale Anforderungen


=== 9.1 Qualitätsziele

1 = Nicht wichtig
2 = Sehr wichtig
[options="header", cols="3h, ^1, ^1, ^1, ^1, ^1"]
|===
|Qualitätsanforderung | 1 | 2 | 3 | 4 | 5
|Wartbarkeit          |   |   |   | x | 
|Anwendbarkeit        |   |   | x |   | 
|Sicherheit           |   |   | x |   | 
|===

Dokumentieren Sie in einer Tabelle die Qualitätsziele, welche das System erreichen soll, sowie deren Priorität.

=== 9.2 Konkrete Nicht-Funktionale Anforderungen

[options="header"]
[cols="1, 1, 1, 1, 4"]
|===
|ID     |Version  |Name           |Beschreibung
|[NF01] |v0.1     |Wartbarkeit    |Gut getesteter Software, um möglichst viele Fehler abzudecken.
|[NF02] |v0.1     |               |


Beschreiben Sie Nicht-Funktionale Anforderungen, welche dazu dienen, die zuvor definierten Qualitätsziele zu erreichen.
Achten Sie darauf, dass deren Erfüllung (mindestens theoretisch) messbar sein muss.

== 10. GUI Prototyp

In diesem Kapitel soll ein Entwurf der Navigationsmöglichkeiten und Dialoge des Systems erstellt werden.
Idealerweise entsteht auch ein grafischer Prototyp, welcher dem Kunden zeigt, wie sein System visuell umgesetzt werden soll.
Konkrete Absprachen - beispielsweise ob der grafische Prototyp oder die Dialoglandkarte höhere Priorität hat - sind mit dem Kunden zu treffen.

=== 10.1 Überblick: Dialoglandkarte
Erstellen Sie ein Übersichtsdiagramm, das das Zusammenspiel Ihrer Masken zur Laufzeit darstellt. Also mit welchen Aktionen zwischen den Masken navigiert wird.
//Die nachfolgende Abbildung zeigt eine an die Pinnwand gezeichnete Dialoglandkarte. Ihre Karte sollte zusätzlich die Buttons/Funktionen darstellen, mit deren Hilfe Sie zwischen den Masken navigieren.

=== 10.2 Dialogbeschreibung
Für jeden Dialog:

1. Kurze textuelle Dialogbeschreibung eingefügt: Was soll der jeweilige Dialog? Was kann man damit tun? Überblick?
2. Maskenentwürfe (Screenshot, Mockup)
3. Maskenelemente (Ein/Ausgabefelder, Aktionen wie Buttons, Listen, …)
4. Evtl. Maskendetails, spezielle Widgets

== 11. Datenmodell

=== 11.1 Überblick: Klassendiagramm
UML-Analyseklassendiagramm

=== 11.2 Klassen und Enumerationen
Dieser Abschnitt stellt eine Vereinigung von Glossar und der Beschreibung von Klassen/Enumerationen dar. Jede Klasse und Enumeration wird in Form eines Glossars textuell beschrieben. Zusätzlich werden eventuellen Konsistenz- und Formatierungsregeln aufgeführt.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="header"]
|===
|Klasse/Enumeration |Beschreibung |
|…                  |…            |
|===

== 12. Akzeptanztestfälle
Mithilfe von Akzeptanztests wird geprüft, ob die Software die funktionalen Erwartungen und Anforderungen im Gebrauch erfüllt. Diese sollen und können aus den Anwendungsfallbeschreibungen und den UML-Sequenzdiagrammen abgeleitet werden. D.h., pro (komplexen) Anwendungsfall gibt es typischerweise mindestens ein Sequenzdiagramm (welches ein Szenarium beschreibt). Für jedes Szenarium sollte es einen Akzeptanztestfall geben. Listen Sie alle Akzeptanztestfälle in tabellarischer Form auf.
Jeder Testfall soll mit einer ID versehen werde, um später zwischen den Dokumenten (z.B. im Test-Plan) referenzieren zu können.

== 13. Glossar
Sämtliche Begriffe, die innerhalb des Projektes verwendet werden und deren gemeinsames Verständnis aller beteiligten Stakeholder essentiell ist, sollten hier aufgeführt werden.
Insbesondere Begriffe der zu implementierenden Domäne wurden bereits beschrieben, jedoch gibt es meist mehr Begriffe, die einer Beschreibung bedürfen. +
Beispiel: Was bedeutet "Kunde"? Ein Nutzer des Systems? Der Kunde des Projektes (Auftraggeber)?

== 14. Offene Punkte
Offene Punkte werden entweder direkt in der Spezifikation notiert. Wenn das Pflichtenheft zum finalen Review vorgelegt wird, sollte es keine offenen Punkte mehr geben.
