= Zeiterfassung für Gruppe 09

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |Mirek Kral |Yuju Chen |Song Bai |Yutian Lei |Sophie Schulze |Meeting
|1     |400   |120    |180    |360    |360    |60    
|2     |1050   |430    |420    |510    |420    |52    
|3     |1100   |1020    |960    |900    |1170    |40
|4    |…   |…    |…    |…    |…    |…        
|5    |…   |…    |…    |…    |…    |…        
|6    |…   |…    |…    |…    |…    |…        
|7    |…   |…    |…    |…    |…    |…        
|8    |…   |…    |…    |…    |…    |…        
|9    |…   |…    |…    |…    |…    |…        
|10   |…   |…    |…    |…    |…    |…        
|11   |…   |…    |…    |…    |…    |…        
|12   |…   |…    |…    |…    |…    |…        
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
