= Persönliches Feedback eines Teammitgliedes des Softwarepraktikums 2021/22
// Auch wenn der Bogen nicht anonymisiert ist, dürfen Sie gern Ihre Meinung offen kundtun.
// Sowohl positive als auch negative Anmerkungen werden gern gesehen und zur stetigen Verbesserung genutzt.
// Versuchen Sie in dieser Auswertung also stets sowohl Positives wie auch Negatives zu erwähnen.

**Von: Song Bai**

**Gruppe: swt21w09**

== Was habe ich gelernt / was habe ich nicht gelernt?
// Ausführung der positiven und negativen Erfahrungen, die im Softwarepraktikum gesammelt wurden
Da ich nicht nur über Component-Customer sondern auch über Forum gearbeitet habe, habe ich meine Java- und HTML-Kenntnisse signifikant verbessert.
Besonders habe ich den Umfang mit Spring, Salespoint und Thymeleaf viel gelernt.

Und ich finde,dass Videoshop sehr hilfreich als VollbildProjekt setzen zu sein. Im Laufe des Projektes schaue ich oft die Ideen der Implementierung im Videoshop nach.

== Welche Erfahrungen habe ich mit der Zusammenarbeit im Team gemacht?
// Kurze Beschreibung der Zusammenarbeit im Team. Was lief gut? Was war verbesserungswürdig? Was würden Sie das nächste Mal anders machen?
Am Anfang des Projektes war die Zusammenarbeit tatsächlich sehr schwierig, weil wir nicht kennengelernt haben , und jeder hatte seine selben Ideen.

Aus diese Weise haben wir das Bescheid zuerst, uns mal vorzustellen und über alles Mögliche zu unterhalten. Das hat uns viel geholfen und nachher 
haben wir viel effektiver darauf durchgeführt. Sogar wegen Corona Pandemie wurde die Kommunikation beschränkt, haben wir auch noch präzens getroffen.

Jeder hat mehr oder weniger beigetragen und jeder spielt eine wichtige Rolle.

== Welche Erfahrungen habe ich bei der Wiederverwendung von Bibliotheken/Frameworks (insbesondere SalesPoint) gemacht?
// Einschätzung der Arbeit mit den bereitgestellten und zusätzlich genutzten Frameworks. Was War gut? Was war verbesserungswürdig?
Bezüglich Spring und Thymeleaf hatte ich keine größeren Probleme und fand die Frameworks auch sehr gut einsetzbar.

Das Gleiche kann ich über Salespoint leider nicht behaupten.

z.B Als ich die Funktion "Change Password" implementiert habe, gab es immer Probleme Encrypt. Passwort mit Zeichenkette(altes Passwort) zu vergleichen. Ich musste erst String zu Encrypt. Passwort wechseln, was ich keinen Weg fand. Ich konnte nur die vorhandene Funktion, die in UserAccount liegt, Change password aufrufen.


== Welche Vorschläge zur weiteren Verbesserung des Softwarepraktikums gibt es?
// Möglichst mit Beschreibung, warum die Umsetzung des von Ihnen angebrachten Vorschlages nötig ist.
Ich hoffe, dass die Beschreibung und die Verwendung der Methoden sowie der Annotationen von Salespoint Framework mehr deutlicher wären.

== Feedback für den Tutor
// Fühlten Sie sich durch den vom Lehrstuhl bereitgestellten Tutor gut betreut? Was war positiv? Was war verbesserungswürdig?
Ich fand die Betreuung durch unseren Tutor immer angenehm. Ich fand den Tutor auch sehr nett.

== Sonstiges und Anmerkungen
// Welche Aspekte fanden in den oben genannten Punkten keine Erwähnung?
